services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: wallet_test
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=wallet_user
      - DB_PASSWORD=wallet_password
      - DB_NAME=wallet_test
      - DB_URL=postgresql+asyncpg://wallet_user:wallet_password@db:5432/wallet_test
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src

volumes:
  pgdata:
