"""Add operations model

Revision ID: 994e6937ad4f
Revises: 1c5977b368af
Create Date: 2026-03-02 22:58:00.500761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "994e6937ad4f"
down_revision: Union[str, Sequence[str], None] = "1c5977b368af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operations",
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("operation_type", sa.Enum("DEPOSIT", "WITHDRAW", name="operation_type_enum"), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("balance_after", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_wallet_ops_amount_positive"),
        sa.CheckConstraint("balance_after >= 0", name="ck_wallet_ops_balance_after_non_negative"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_id", "idempotency_key", name="uq_wallet_ops_wallet_id_idempotency_key"),
    )
    op.create_index(op.f("ix_operations_wallet_id"), "operations", ["wallet_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operations_wallet_id"), table_name="operations")
    op.drop_table("operations")
    # ### end Alembic commands ###
